### ISSUE TITLE
파이프라인 완성시켰는데 문제가 하나 있어서 공유하고자 합니다

### ISSUE THREAD

**Issue by Tiabet** [kyeul611/CoDA#34]
아까 낮에 제가 팀장님한테 안 없어지는 ㅎ이 있다고 말씀드렸는데요.
전각문자 제거 등 이런저런 걸 해보다가 문제가 뭔지 알았습니다.
알고 보니 저 ㅎ 이 ㅎ 이 아니라 ᄒ 인 것이죠...

자세히 봤더니 ㅎ이 한 글자로 있는게 아니라 
'한' 에서 ㅎ 처럼 (국어 용어가 생각이 안나는데) 윗칸에 위치한다는 사실을 알아냈습니다.

그런데 문제는 저사람이 일부러 ᄒ 을 써서 저것만 그런 것이 아니라 
어떤 분이 작성한 리뷰에선
'위자ᅩ아ᅡᅵᅥ쟈덷제ᅦᅦᄌ쟈쟈'
처럼 모든 한글에 대해 저런 오탈자가 발생했다는 것입니다. 

제가 궁금한 건..
1. 네이버 쇼핑 리뷰에서 저런 글자를 대체 어떻게 쓸 수 있는 건지
2. 만에하나 크롤링 과정에서 수정이 가능할지??

크롤링 과정에서 수정이 불가능할 것 같은 느낌이 들어서
혹시 팀원분 중에 저 윗칸에 글자를 입력하는 법을 아시는 분이 계시면 알려주십시요...

**Comment by kyeul611** [comment]
ㅋㅋㅋ 아니 무슨 저런 글자가!? 살다살다 저런건 처음 보네요.

**Comment by Tiabet** [comment]
이상 텍스트 문제 해결했습니다! 정규식 방식을 조금 바꿔보았습니다
최종 파이프라인은 내일 중으로 push 하겠습니다
'파이프라인' '파이프라인 만들때 연습한 코드' '적용한 결과물' 중에 최종 파이프라인만 push할까요?

**Comment by kyeul611** [comment]
동일한 아스키에 여러 텍스트가 있다니.. 이럴 수도 있다니 신기하네요ㄷㄷ
