### ISSUE TITLE
로우데이터 전처리 전에 파일 병합에 대해서 어떻게 하면 좋을까요?

### ISSUE THREAD

**Issue by kyeul611** [kyeul611/CoDA#37]
지금 생각중인 옵션은 아래와 같습니다. 
사소한 고민일 수도 있는데, 팀원들의 고견을 구합니다 ~_~

1. 병합 없이 각각의 파일에 전처리를 진행하고 별도로 저장한다. 
    - 전처리가 중간에 중단되더라도 수행이 완료된 코드를 안전하게 확보할 수 있음
2. 전처리 파일 내부에서 병합 코드를 포함시킨다. 
    - 전처리 진행할 때 데이터가 있는 폴더를 input으로 받음
    - 한번에 모든 것이 해결~
3. 병합 코드를 따로 작성한다. 
    - 전처리와 병합을 선택적으로 수행할 수 있다.
4. 전부 다 한다

**Comment by Tiabet** [comment]
AWS 같은 클라우드 환경에서 10시간 넘게 코드를 돌린다고 가정하면 전처리가 중간에 중단될 확률이 얼마나 될까요?

**Comment by Tiabet** [comment]
특별히 의견이 없으시네요?? 제가 생각했을 땐... 병합파일은 우선 따로 만들어 놓는 것이 안전한 선택이라고 보입니다. 선전처리-후병합, 선병합-후전처리 둘 다 계산 시간은 비슷할 것으로 보이지만 AWS에서 먼저 해보고 너무 계산이 느리다, 많이 걸린다 싶으면 그때 조금이나마 더 유연하게 돌릴 수 있을 것 같고, 혹여나 병합파일은 나중에 블로그 파일이라던지 따로 쓰일 곳이 있을 수도 있겠다 싶네요. 그래서 저는 병합파일과 전처리 파일을 따로 만들되, 둘다 input으로는 폴더명을 받아서 병합 파일은 그 폴더 안에 있는 모든 파일 합치기, 전처리 파일은 그 폴더 안에 있는 각각의 파일 전처리해서 각각 저장하기 이 방식으로 하겠습니다!

**Comment by kyeul611** [comment]
@Tiabet 선 병합 시에 연산 시간은 나눠서 입력하는 게 IO 시간이 조금 소요 될 것 같은데, 큰 차이는 안 생기지 않을까 싶어요. 다만 병합해서 진행하면 메모리도 많이 차지하는 이슈는 있을 것 같아요. AWS가 아닌 로컬에서는 큰 문제 안될 것 같긴 한데,,  아무튼 그렇습니다.
