### ISSUE TITLE
이슈까지는 아닌데, 사용 안되는 변수가 있어서 없애도 될 것 같습니다.

### ISSUE THREAD

**Issue by kyeul611** [kyeul611/CoDA#47]
https://github.com/kyeul611/CoDA/blob/a4b8e153f49c1b329a19c99486216802369bc3ac/DA/text_preprocessing_pipeline.py#L60C5-L60C17

**Comment by Tiabet** [comment]
60번째 줄의 input_foler는 _로 처리하는게 좋을 것 같습니다~ 제가 고쳐서 풀리퀘하겠습니다
