### ISSUE TITLE
Selenium 멀티프로세싱으로 작업시 Permission deny 발생

### ISSUE THREAD

**Issue by SorryKim** [kyeul611/CoDA#49]
multiprocessing을 아무리 해봐도 안됩니다......
터미널 2개켜서 수동으로 멀티프로세싱을 진행하는 것도 안됩니다.... help

**Comment by kyeul611** [comment]
아 레퍼런스 찾아주기로 했는데 깜ㅃ가햇네

**Comment by SorryKim** [comment]
크롬드라이버를 최신버젼으로 적용시키니 해결됐습니다 하하하
